### ISSUE TITLE
There's no already built ROM

### ISSUE THREAD

**Issue by SantX27** [opensource591/device_samsung_heatnfc3g#1]
Dear @opensource591 I'm really interested in this project and I really want to flash this CM but I can't compile it from myself 'cause my old PC. Please make it flashable as a IMG-or-whatever. I have already tried porting Philz recovery for heatnfc3g without success.

**Comment by berkantkz** [comment]
No one has this device I suppose in our team. Yeah, we have this repository but although, I don't suppose no one is sure this tree will work, at least, I'm not.

**Comment by SantX27** [comment]
Oh, well then I propose myself as beta tester

**Comment by androidlover5842** [comment]
contact me on hangouts if you want cm13 or + id = androidlover5842@gmail.com
